[package]
name = "erc20_oz100"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.4"
openzeppelin = "1.0.0" 

[[target.starknet-contract]]
sierra = true
casm = true
